# exclude: "^(?!backend/)" # Only run for the backend folder
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=88]
        files: '\.py$' # Only run for .py files
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: '\.py$' # Only run for .py files
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  #       args: ["--max-line-length=88", "--extend-ignore=E203"]
  #       files: '\.py$' # Only run for .py files
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.910
  #   hooks:
  #     - id: mypy
  #       args: ["--strict"]
  #       files: '\.py$' # Only run for .py files
