"""create_organization

Revision ID: 43fcee9accc7
Revises: 5a68bdd27ef3
Create Date: 2023-12-20 12:08:19.532584

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "43fcee9accc7"
down_revision = "5a68bdd27ef3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pk", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("verification_mode_types", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=70), nullable=False),
        sa.Column("name_chars", sa.VARCHAR(length=70), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("line_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "organization_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "owner_first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "owner_last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verification_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "verification_document", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("default_wallet_currency", sa.String(length=15), nullable=False),
        sa.Column("created_by_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "created_by_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(
        op.f("ix_organizations_created_by_id"),
        "organizations",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations_email"), "organizations", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_organizations_name_chars"),
        "organizations",
        ["name_chars"],
        unique=True,
    )
    op.create_index(
        op.f("ix_organizations_owner_id"), "organizations", ["owner_id"], unique=True
    )
    op.create_index(op.f("ix_organizations_pk"), "organizations", ["pk"], unique=False)
    op.create_index(
        op.f("ix_organizations_uuid"), "organizations", ["uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organizations_uuid"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_pk"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_owner_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name_chars"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_email"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_created_by_id"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
