"""add_user_oauth2_scopes

Revision ID: 5a68bdd27ef3
Revises: 86a5a6f99850
Create Date: 2023-11-15 21:54:09.970727

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5a68bdd27ef3'
down_revision = '86a5a6f99850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth2_scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth2_scopes')
    # ### end Alembic commands ###