"""make organization owner mobile optional

Revision ID: 81916dc4793f
Revises: 8d396dda02df
Create Date: 2023-04-16 11:25:15.349928

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81916dc4793f'
down_revision = '8d396dda02df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organizations', 'national_mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'national_mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organizations', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
