"""add_user_demographics

Revision ID: 86a5a6f99850
Revises: ac944c262643
Create Date: 2023-11-15 21:53:01.978621

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "86a5a6f99850"
down_revision = "ac944c262643"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column(
        "users", sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("nationality", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("national_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "national_id_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "users", sa.Column("is_identity_verified", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_identity_verified")
    op.drop_column("users", "national_id_type")
    op.drop_column("users", "national_id")
    op.drop_column("users", "nationality")
    op.drop_column("users", "gender")
    op.drop_column("users", "birth_date")
    # ### end Alembic commands ###
