"""setup_organization_members

Revision ID: 8c5ed6379ac3
Revises: 0b0c3440131f
Create Date: 2022-12-17 02:23:38.944963

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8c5ed6379ac3'
down_revision = '0b0c3440131f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_used_organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_used_organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_used_organization_id')
    op.drop_column('users', 'last_used_organization_name')
