"""transactions

Revision ID: 8d396dda02df
Revises: 97e9500bcc7f
Create Date: 2023-02-09 03:56:00.111203

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8d396dda02df'
down_revision = '97e9500bcc7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bill_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('service_or_product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_service_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checkout_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mode_of_payment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('card_ending_digits', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mobile_money_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mobile_money_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_account_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.uuid'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['product_id'], ['events.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_bill_id'), 'transactions', ['bill_id'], unique=False)
    op.create_index(op.f('ix_transactions_customer_email'), 'transactions', ['customer_email'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_customer_mobile'), 'transactions', ['customer_mobile'], unique=False)
    op.create_index(op.f('ix_transactions_customer_name'), 'transactions', ['customer_name'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_product_id'), 'transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_transactions_uuid'), 'transactions', ['uuid'], unique=True)
    op.add_column('bills', sa.Column('transaction_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.alter_column('bills', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_bills_transaction_id'), 'bills', ['transaction_id'], unique=False)
    op.create_foreign_key(None, 'bills', 'transactions', ['transaction_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_index(op.f('ix_bills_transaction_id'), table_name='bills')
    op.alter_column('bills', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bills', 'charge')
    op.drop_column('bills', 'transaction_id')
    op.drop_index(op.f('ix_transactions_uuid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_product_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_mobile'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_email'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_bill_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
