"""create_wallet

Revision ID: 8edb44ce233c
Revises: 43fcee9accc7
Create Date: 2023-12-28 22:19:06.054624

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "8edb44ce233c"
down_revision = "43fcee9accc7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pk", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("currency", sa.String(length=15), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "managing_organization_id", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column(
            name="balance",
            type_=sa.DECIMAL(precision=18, scale=2),
            nullable=False,
            comment="Wallet balance",
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "managing_organization_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("owner_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_mobile", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["managing_organization_id"],
            ["organizations.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "owner_id",
            "managing_organization_id",
            name="wallet__owner_managing_organization_uc",
        ),
    )
    op.create_index(op.f("ix_wallets_currency"), "wallets", ["currency"], unique=False)
    op.create_index(
        op.f("ix_wallets_description"), "wallets", ["description"], unique=True
    )
    op.create_index(
        op.f("ix_wallets_managing_organization_id"),
        "wallets",
        ["managing_organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_wallets_owner_id"), "wallets", ["owner_id"], unique=False)
    op.create_index(op.f("ix_wallets_pk"), "wallets", ["pk"], unique=False)
    op.create_index(op.f("ix_wallets_status"), "wallets", ["status"], unique=False)
    op.create_index(op.f("ix_wallets_uuid"), "wallets", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_uuid"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_status"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_pk"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_owner_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_managing_organization_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_description"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_currency"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
