"""bills

Revision ID: 97e9500bcc7f
Revises: aa40dea29fbf
Create Date: 2023-02-07 10:39:07.706000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '97e9500bcc7f'
down_revision = 'aa40dea29fbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('service_or_product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True, default=1),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False, default=""),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.uuid'], ),
    sa.ForeignKeyConstraint(['product_id'], ['courses.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_customer_email'), 'bills', ['customer_email'], unique=False)
    op.create_index(op.f('ix_bills_customer_id'), 'bills', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bills_customer_mobile'), 'bills', ['customer_mobile'], unique=False)
    op.create_index(op.f('ix_bills_customer_name'), 'bills', ['customer_name'], unique=False)
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_bills_organization_id'), 'bills', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bills_organization_name'), 'bills', ['organization_name'], unique=False)
    op.create_index(op.f('ix_bills_product_id'), 'bills', ['product_id'], unique=False)
    op.create_index(op.f('ix_bills_uuid'), 'bills', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_uuid'), table_name='bills')
    op.drop_index(op.f('ix_bills_product_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_organization_name'), table_name='bills')
    op.drop_index(op.f('ix_bills_organization_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_customer_name'), table_name='bills')
    op.drop_index(op.f('ix_bills_customer_mobile'), table_name='bills')
    op.drop_index(op.f('ix_bills_customer_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_customer_email'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
