"""make uuid unique

Revision ID: bc98e4a4101d
Revises: cf35762b4713
Create Date: 2022-11-26 23:14:55.319400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bc98e4a4101d'
down_revision = 'cf35762b4713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_uuid', table_name='otp')
    op.create_index(op.f('ix_otp_uuid'), 'otp', ['uuid'], unique=True)
    op.drop_index('ix_users_uuid', table_name='users')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_index('ix_users_uuid', 'users', ['uuid'], unique=False)
    op.drop_index(op.f('ix_otp_uuid'), table_name='otp')
    op.create_index('ix_otp_uuid', 'otp', ['uuid'], unique=False)
    # ### end Alembic commands ###
