"""create_otp_table

Revision ID: cf35762b4713
Revises: b1fd0e2fb2ff
Create Date: 2022-11-15 15:59:41.196672

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf35762b4713"
down_revision = "b1fd0e2fb2ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_otp_id"), "otp", ["id"], unique=False)
    op.create_index(op.f("ix_otp_user_id"), "otp", ["user_id"], unique=False)
    op.create_index(op.f("ix_otp_uuid"), "otp", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_otp_uuid"), table_name="otp")
    op.drop_index(op.f("ix_otp_user_id"), table_name="otp")
    op.drop_index(op.f("ix_otp_id"), table_name="otp")
    op.drop_table("otp")
    # ### end Alembic commands ###
