"""add_token_type_to_otp

Revision ID: eded1457bdee
Revises: 7c220088e286
Create Date: 2023-05-20 16:41:43.428748

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'eded1457bdee'
down_revision = '7c220088e286'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), default='user_verification'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp', 'token_type')
    # ### end Alembic commands ###
